kind: Secret
apiVersion: v1
metadata:
  name: thanos-object-storage-secret
  namespace: {{ .Release.Namespace }}
stringData:
  thanos.yaml: |
    type: S3
    config:
      bucket: {{ .Values.objectStorage.bucket | quote }}
      endpoint: {{ .Values.objectStorage.endpoint | quote }}
      access_key: {{ .Values.objectStorage.accessKey | quote }}
      secret_key: {{ .Values.objectStorage.secretKey | quote }}
      http_config:
        tls_config:
          ca_file: /etc/thanos/certs/public.crt
    prefix: {{ .Values.objectStorage.prefix | quote }}
type: Opaque
