//go:build !ignore_autogenerated

/*
Copyright AppsCode Inc. and Contributors

Licensed under the AppsCode Community License 1.0.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/appscode/licenses/raw/1.0.0/AppsCode-Community-1.0.0.md

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiserverSpec) DeepCopyInto(out *ApiserverSpec) {
	*out = *in
	out.Healthcheck = in.Healthcheck
	out.ServingCerts = in.ServingCerts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiserverSpec.
func (in *ApiserverSpec) DeepCopy() *ApiserverSpec {
	if in == nil {
		return nil
	}
	out := new(ApiserverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppscodeOtelStack) DeepCopyInto(out *AppscodeOtelStack) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppscodeOtelStack.
func (in *AppscodeOtelStack) DeepCopy() *AppscodeOtelStack {
	if in == nil {
		return nil
	}
	out := new(AppscodeOtelStack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppscodeOtelStack) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppscodeOtelStackList) DeepCopyInto(out *AppscodeOtelStackList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppscodeOtelStack, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppscodeOtelStackList.
func (in *AppscodeOtelStackList) DeepCopy() *AppscodeOtelStackList {
	if in == nil {
		return nil
	}
	out := new(AppscodeOtelStackList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppscodeOtelStackList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppscodeOtelStackSpec) DeepCopyInto(out *AppscodeOtelStackSpec) {
	*out = *in
	in.OpentelemetryKubeStack.DeepCopyInto(&out.OpentelemetryKubeStack)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppscodeOtelStackSpec.
func (in *AppscodeOtelStackSpec) DeepCopy() *AppscodeOtelStackSpec {
	if in == nil {
		return nil
	}
	out := new(AppscodeOtelStackSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BasicAuth) DeepCopyInto(out *BasicAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BasicAuth.
func (in *BasicAuth) DeepCopy() *BasicAuth {
	if in == nil {
		return nil
	}
	out := new(BasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraSecret) DeepCopyInto(out *CassandraSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraSecret.
func (in *CassandraSecret) DeepCopy() *CassandraSecret {
	if in == nil {
		return nil
	}
	out := new(CassandraSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraSpec) DeepCopyInto(out *CassandraSpec) {
	*out = *in
	out.Image = in.Image
	in.LivenessProbe.DeepCopyInto(&out.LivenessProbe)
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraSpec.
func (in *CassandraSpec) DeepCopy() *CassandraSpec {
	if in == nil {
		return nil
	}
	out := new(CassandraSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CleanerRef) DeepCopyInto(out *CleanerRef) {
	*out = *in
	out.ImageRef = in.ImageRef
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CleanerRef.
func (in *CleanerRef) DeepCopy() *CleanerRef {
	if in == nil {
		return nil
	}
	out := new(CleanerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Container) DeepCopyInto(out *Container) {
	*out = *in
	out.ImageRef = in.ImageRef
	in.Resources.DeepCopyInto(&out.Resources)
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Container.
func (in *Container) DeepCopy() *Container {
	if in == nil {
		return nil
	}
	out := new(Container)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsSpec) DeepCopyInto(out *DnsSpec) {
	*out = *in
	if in.TargetIPs != nil {
		in, out := &in.TargetIPs, &out.TargetIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsSpec.
func (in *DnsSpec) DeepCopy() *DnsSpec {
	if in == nil {
		return nil
	}
	out := new(DnsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalPostgresql) DeepCopyInto(out *ExternalPostgresql) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalPostgresql.
func (in *ExternalPostgresql) DeepCopy() *ExternalPostgresql {
	if in == nil {
		return nil
	}
	out := new(ExternalPostgresql)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlowrootSpec) DeepCopyInto(out *GlowrootSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlowrootSpec.
func (in *GlowrootSpec) DeepCopy() *GlowrootSpec {
	if in == nil {
		return nil
	}
	out := new(GlowrootSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthcheckSpec) DeepCopyInto(out *HealthcheckSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthcheckSpec.
func (in *HealthcheckSpec) DeepCopy() *HealthcheckSpec {
	if in == nil {
		return nil
	}
	out := new(HealthcheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageRef) DeepCopyInto(out *ImageRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageRef.
func (in *ImageRef) DeepCopy() *ImageRef {
	if in == nil {
		return nil
	}
	out := new(ImageRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageReference) DeepCopyInto(out *ImageReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageReference.
func (in *ImageReference) DeepCopy() *ImageReference {
	if in == nil {
		return nil
	}
	out := new(ImageReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboxAgent) DeepCopyInto(out *InboxAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboxAgent.
func (in *InboxAgent) DeepCopy() *InboxAgent {
	if in == nil {
		return nil
	}
	out := new(InboxAgent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InboxAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboxAgentApiserver) DeepCopyInto(out *InboxAgentApiserver) {
	*out = *in
	out.Healthcheck = in.Healthcheck
	out.ServingCerts = in.ServingCerts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboxAgentApiserver.
func (in *InboxAgentApiserver) DeepCopy() *InboxAgentApiserver {
	if in == nil {
		return nil
	}
	out := new(InboxAgentApiserver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboxAgentList) DeepCopyInto(out *InboxAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InboxAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboxAgentList.
func (in *InboxAgentList) DeepCopy() *InboxAgentList {
	if in == nil {
		return nil
	}
	out := new(InboxAgentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InboxAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboxAgentSpec) DeepCopyInto(out *InboxAgentSpec) {
	*out = *in
	in.Operator.DeepCopyInto(&out.Operator)
	in.RbacProxy.DeepCopyInto(&out.RbacProxy)
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
	out.Apiserver = in.Apiserver
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	out.InboxServer = in.InboxServer
	out.Distro = in.Distro
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboxAgentSpec.
func (in *InboxAgentSpec) DeepCopy() *InboxAgentSpec {
	if in == nil {
		return nil
	}
	out := new(InboxAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboxServer) DeepCopyInto(out *InboxServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboxServer.
func (in *InboxServer) DeepCopy() *InboxServer {
	if in == nil {
		return nil
	}
	out := new(InboxServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InboxServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboxServerDistributed) DeepCopyInto(out *InboxServerDistributed) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboxServerDistributed.
func (in *InboxServerDistributed) DeepCopy() *InboxServerDistributed {
	if in == nil {
		return nil
	}
	out := new(InboxServerDistributed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InboxServerDistributed) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboxServerDistributedList) DeepCopyInto(out *InboxServerDistributedList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InboxServerDistributed, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboxServerDistributedList.
func (in *InboxServerDistributedList) DeepCopy() *InboxServerDistributedList {
	if in == nil {
		return nil
	}
	out := new(InboxServerDistributedList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InboxServerDistributedList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboxServerDistributedSpec) DeepCopyInto(out *InboxServerDistributedSpec) {
	*out = *in
	in.Dns.DeepCopyInto(&out.Dns)
	in.James.DeepCopyInto(&out.James)
	in.ServiceMonitor.DeepCopyInto(&out.ServiceMonitor)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.AdminIngress.DeepCopyInto(&out.AdminIngress)
	in.Cassandra.DeepCopyInto(&out.Cassandra)
	out.Opensearch = in.Opensearch
	out.Rabbitmq = in.Rabbitmq
	out.S3 = in.S3
	out.Tika = in.Tika
	out.Service = in.Service
	out.Distro = in.Distro
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboxServerDistributedSpec.
func (in *InboxServerDistributedSpec) DeepCopy() *InboxServerDistributedSpec {
	if in == nil {
		return nil
	}
	out := new(InboxServerDistributedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboxServerInfo) DeepCopyInto(out *InboxServerInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboxServerInfo.
func (in *InboxServerInfo) DeepCopy() *InboxServerInfo {
	if in == nil {
		return nil
	}
	out := new(InboxServerInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboxServerList) DeepCopyInto(out *InboxServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InboxServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboxServerList.
func (in *InboxServerList) DeepCopy() *InboxServerList {
	if in == nil {
		return nil
	}
	out := new(InboxServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InboxServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboxServerMigrateSpec) DeepCopyInto(out *InboxServerMigrateSpec) {
	*out = *in
	out.Image = in.Image
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboxServerMigrateSpec.
func (in *InboxServerMigrateSpec) DeepCopy() *InboxServerMigrateSpec {
	if in == nil {
		return nil
	}
	out := new(InboxServerMigrateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InboxServerSpec) DeepCopyInto(out *InboxServerSpec) {
	*out = *in
	in.Dns.DeepCopyInto(&out.Dns)
	in.James.DeepCopyInto(&out.James)
	in.ServiceMonitor.DeepCopyInto(&out.ServiceMonitor)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.AdminIngress.DeepCopyInto(&out.AdminIngress)
	in.Postgresql.DeepCopyInto(&out.Postgresql)
	in.Migrate.DeepCopyInto(&out.Migrate)
	out.Distro = in.Distro
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InboxServerSpec.
func (in *InboxServerSpec) DeepCopy() *InboxServerSpec {
	if in == nil {
		return nil
	}
	out := new(InboxServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JamesDistributedEnv) DeepCopyInto(out *JamesDistributedEnv) {
	*out = *in
	out.Glowroot = in.Glowroot
	in.JamesResources.DeepCopyInto(&out.JamesResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JamesDistributedEnv.
func (in *JamesDistributedEnv) DeepCopy() *JamesDistributedEnv {
	if in == nil {
		return nil
	}
	out := new(JamesDistributedEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JamesDistributedSpec) DeepCopyInto(out *JamesDistributedSpec) {
	*out = *in
	in.Env.DeepCopyInto(&out.Env)
	out.TLS = in.TLS
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(JamesSecret)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JamesDistributedSpec.
func (in *JamesDistributedSpec) DeepCopy() *JamesDistributedSpec {
	if in == nil {
		return nil
	}
	out := new(JamesDistributedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JamesEnv) DeepCopyInto(out *JamesEnv) {
	*out = *in
	out.Glowroot = in.Glowroot
	in.JamesResources.DeepCopyInto(&out.JamesResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JamesEnv.
func (in *JamesEnv) DeepCopy() *JamesEnv {
	if in == nil {
		return nil
	}
	out := new(JamesEnv)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JamesSecret) DeepCopyInto(out *JamesSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JamesSecret.
func (in *JamesSecret) DeepCopy() *JamesSecret {
	if in == nil {
		return nil
	}
	out := new(JamesSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JamesSpec) DeepCopyInto(out *JamesSpec) {
	*out = *in
	in.Env.DeepCopyInto(&out.Env)
	out.TLS = in.TLS
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(JamesSecret)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JamesSpec.
func (in *JamesSpec) DeepCopy() *JamesSpec {
	if in == nil {
		return nil
	}
	out := new(JamesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoring) DeepCopyInto(out *Monitoring) {
	*out = *in
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(ServiceMonitorLabels)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoring.
func (in *Monitoring) DeepCopy() *Monitoring {
	if in == nil {
		return nil
	}
	out := new(Monitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySpec.
func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpensearchSecret) DeepCopyInto(out *OpensearchSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpensearchSecret.
func (in *OpensearchSecret) DeepCopy() *OpensearchSecret {
	if in == nil {
		return nil
	}
	out := new(OpensearchSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpensearchSpec) DeepCopyInto(out *OpensearchSpec) {
	*out = *in
	out.Image = in.Image
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpensearchSpec.
func (in *OpensearchSpec) DeepCopy() *OpensearchSpec {
	if in == nil {
		return nil
	}
	out := new(OpensearchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpentelemetryFeatureFlag) DeepCopyInto(out *OpentelemetryFeatureFlag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpentelemetryFeatureFlag.
func (in *OpentelemetryFeatureFlag) DeepCopy() *OpentelemetryFeatureFlag {
	if in == nil {
		return nil
	}
	out := new(OpentelemetryFeatureFlag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpentelemetryKubeStackCollectors) DeepCopyInto(out *OpentelemetryKubeStackCollectors) {
	*out = *in
	in.Daemon.DeepCopyInto(&out.Daemon)
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpentelemetryKubeStackCollectors.
func (in *OpentelemetryKubeStackCollectors) DeepCopy() *OpentelemetryKubeStackCollectors {
	if in == nil {
		return nil
	}
	out := new(OpentelemetryKubeStackCollectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpentelemetryKubeStackValues) DeepCopyInto(out *OpentelemetryKubeStackValues) {
	*out = *in
	if in.OpentelemetryOperator != nil {
		in, out := &in.OpentelemetryOperator, &out.OpentelemetryOperator
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	out.AdmissionWebhooks = in.AdmissionWebhooks
	in.Collectors.DeepCopyInto(&out.Collectors)
	out.Instrumentation = in.Instrumentation
	out.OpAMPBridge = in.OpAMPBridge
	out.KubernetesServiceMonitors = in.KubernetesServiceMonitors
	out.KubeApiServer = in.KubeApiServer
	out.Kubelet = in.Kubelet
	out.KubeControllerManager = in.KubeControllerManager
	out.KubeDns = in.KubeDns
	out.KubeEtcd = in.KubeEtcd
	out.KubeScheduler = in.KubeScheduler
	out.KubeProxy = in.KubeProxy
	out.KubeStateMetrics = in.KubeStateMetrics
	out.NodeExporter = in.NodeExporter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpentelemetryKubeStackValues.
func (in *OpentelemetryKubeStackValues) DeepCopy() *OpentelemetryKubeStackValues {
	if in == nil {
		return nil
	}
	out := new(OpentelemetryKubeStackValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelAdmissionWebhooks) DeepCopyInto(out *OtelAdmissionWebhooks) {
	*out = *in
	out.AutoGenerateCert = in.AutoGenerateCert
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelAdmissionWebhooks.
func (in *OtelAdmissionWebhooks) DeepCopy() *OtelAdmissionWebhooks {
	if in == nil {
		return nil
	}
	out := new(OtelAdmissionWebhooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelAutoGenerateCert) DeepCopyInto(out *OtelAutoGenerateCert) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelAutoGenerateCert.
func (in *OtelAutoGenerateCert) DeepCopy() *OtelAutoGenerateCert {
	if in == nil {
		return nil
	}
	out := new(OtelAutoGenerateCert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelCollector) DeepCopyInto(out *OtelCollector) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(OtelCollectorImage)
		**out = **in
	}
	if in.TargetAllocator != nil {
		in, out := &in.TargetAllocator, &out.TargetAllocator
		*out = new(OtelTargetAllocator)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Presets != nil {
		in, out := &in.Presets, &out.Presets
		*out = new(OtelCollectorPresets)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.HostAliases != nil {
		in, out := &in.HostAliases, &out.HostAliases
		*out = make([]corev1.HostAlias, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelCollector.
func (in *OtelCollector) DeepCopy() *OtelCollector {
	if in == nil {
		return nil
	}
	out := new(OtelCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelCollectorImage) DeepCopyInto(out *OtelCollectorImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelCollectorImage.
func (in *OtelCollectorImage) DeepCopy() *OtelCollectorImage {
	if in == nil {
		return nil
	}
	out := new(OtelCollectorImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelCollectorPresets) DeepCopyInto(out *OtelCollectorPresets) {
	*out = *in
	if in.LogsCollection != nil {
		in, out := &in.LogsCollection, &out.LogsCollection
		*out = new(OtelPresetFlag)
		**out = **in
	}
	if in.HostMetrics != nil {
		in, out := &in.HostMetrics, &out.HostMetrics
		*out = new(OtelPresetFlag)
		**out = **in
	}
	if in.KubeletMetrics != nil {
		in, out := &in.KubeletMetrics, &out.KubeletMetrics
		*out = new(OtelPresetFlag)
		**out = **in
	}
	if in.KubernetesAttributes != nil {
		in, out := &in.KubernetesAttributes, &out.KubernetesAttributes
		*out = new(OtelPresetFlag)
		**out = **in
	}
	if in.ClusterMetrics != nil {
		in, out := &in.ClusterMetrics, &out.ClusterMetrics
		*out = new(OtelPresetFlag)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelCollectorPresets.
func (in *OtelCollectorPresets) DeepCopy() *OtelCollectorPresets {
	if in == nil {
		return nil
	}
	out := new(OtelCollectorPresets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelPresetFlag) DeepCopyInto(out *OtelPresetFlag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelPresetFlag.
func (in *OtelPresetFlag) DeepCopy() *OtelPresetFlag {
	if in == nil {
		return nil
	}
	out := new(OtelPresetFlag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelTargetAllocator) DeepCopyInto(out *OtelTargetAllocator) {
	*out = *in
	if in.PrometheusCR != nil {
		in, out := &in.PrometheusCR, &out.PrometheusCR
		*out = new(OtelTargetAllocatorPromCR)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelTargetAllocator.
func (in *OtelTargetAllocator) DeepCopy() *OtelTargetAllocator {
	if in == nil {
		return nil
	}
	out := new(OtelTargetAllocator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelTargetAllocatorPromCR) DeepCopyInto(out *OtelTargetAllocatorPromCR) {
	*out = *in
	if in.PodMonitorSelector != nil {
		in, out := &in.PodMonitorSelector, &out.PodMonitorSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ServiceMonitorSelector != nil {
		in, out := &in.ServiceMonitorSelector, &out.ServiceMonitorSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelTargetAllocatorPromCR.
func (in *OtelTargetAllocatorPromCR) DeepCopy() *OtelTargetAllocatorPromCR {
	if in == nil {
		return nil
	}
	out := new(OtelTargetAllocatorPromCR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Perses) DeepCopyInto(out *Perses) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Perses.
func (in *Perses) DeepCopy() *Perses {
	if in == nil {
		return nil
	}
	out := new(Perses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Perses) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesConfig) DeepCopyInto(out *PersesConfig) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Security.DeepCopyInto(&out.Security)
	in.Frontend.DeepCopyInto(&out.Frontend)
	out.Database = in.Database
	in.Provisioning.DeepCopyInto(&out.Provisioning)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesConfig.
func (in *PersesConfig) DeepCopy() *PersesConfig {
	if in == nil {
		return nil
	}
	out := new(PersesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesConfigAuthentication) DeepCopyInto(out *PersesConfigAuthentication) {
	*out = *in
	out.Providers = in.Providers
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesConfigAuthentication.
func (in *PersesConfigAuthentication) DeepCopy() *PersesConfigAuthentication {
	if in == nil {
		return nil
	}
	out := new(PersesConfigAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesConfigAuthenticationProviders) DeepCopyInto(out *PersesConfigAuthenticationProviders) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesConfigAuthenticationProviders.
func (in *PersesConfigAuthenticationProviders) DeepCopy() *PersesConfigAuthenticationProviders {
	if in == nil {
		return nil
	}
	out := new(PersesConfigAuthenticationProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesConfigAuthorization) DeepCopyInto(out *PersesConfigAuthorization) {
	*out = *in
	if in.GuestPermissions != nil {
		in, out := &in.GuestPermissions, &out.GuestPermissions
		*out = make([]PersesGuestPermission, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesConfigAuthorization.
func (in *PersesConfigAuthorization) DeepCopy() *PersesConfigAuthorization {
	if in == nil {
		return nil
	}
	out := new(PersesConfigAuthorization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesConfigCookie) DeepCopyInto(out *PersesConfigCookie) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesConfigCookie.
func (in *PersesConfigCookie) DeepCopy() *PersesConfigCookie {
	if in == nil {
		return nil
	}
	out := new(PersesConfigCookie)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesConfigDatabase) DeepCopyInto(out *PersesConfigDatabase) {
	*out = *in
	out.SQL = in.SQL
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesConfigDatabase.
func (in *PersesConfigDatabase) DeepCopy() *PersesConfigDatabase {
	if in == nil {
		return nil
	}
	out := new(PersesConfigDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesConfigDatabaseSQL) DeepCopyInto(out *PersesConfigDatabaseSQL) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesConfigDatabaseSQL.
func (in *PersesConfigDatabaseSQL) DeepCopy() *PersesConfigDatabaseSQL {
	if in == nil {
		return nil
	}
	out := new(PersesConfigDatabaseSQL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesConfigFrontend) DeepCopyInto(out *PersesConfigFrontend) {
	*out = *in
	out.Explorer = in.Explorer
	if in.ImportantDashboards != nil {
		in, out := &in.ImportantDashboards, &out.ImportantDashboards
		*out = make([]PersesImportantDashboard, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesConfigFrontend.
func (in *PersesConfigFrontend) DeepCopy() *PersesConfigFrontend {
	if in == nil {
		return nil
	}
	out := new(PersesConfigFrontend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesConfigFrontendExplorer) DeepCopyInto(out *PersesConfigFrontendExplorer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesConfigFrontendExplorer.
func (in *PersesConfigFrontendExplorer) DeepCopy() *PersesConfigFrontendExplorer {
	if in == nil {
		return nil
	}
	out := new(PersesConfigFrontendExplorer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesConfigProvisioning) DeepCopyInto(out *PersesConfigProvisioning) {
	*out = *in
	if in.Folders != nil {
		in, out := &in.Folders, &out.Folders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesConfigProvisioning.
func (in *PersesConfigProvisioning) DeepCopy() *PersesConfigProvisioning {
	if in == nil {
		return nil
	}
	out := new(PersesConfigProvisioning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesConfigSecurity) DeepCopyInto(out *PersesConfigSecurity) {
	*out = *in
	out.Authentication = in.Authentication
	in.Authorization.DeepCopyInto(&out.Authorization)
	out.Cookie = in.Cookie
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesConfigSecurity.
func (in *PersesConfigSecurity) DeepCopy() *PersesConfigSecurity {
	if in == nil {
		return nil
	}
	out := new(PersesConfigSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesGuestPermission) DeepCopyInto(out *PersesGuestPermission) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesGuestPermission.
func (in *PersesGuestPermission) DeepCopy() *PersesGuestPermission {
	if in == nil {
		return nil
	}
	out := new(PersesGuestPermission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesImage) DeepCopyInto(out *PersesImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesImage.
func (in *PersesImage) DeepCopy() *PersesImage {
	if in == nil {
		return nil
	}
	out := new(PersesImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesImportantDashboard) DeepCopyInto(out *PersesImportantDashboard) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesImportantDashboard.
func (in *PersesImportantDashboard) DeepCopy() *PersesImportantDashboard {
	if in == nil {
		return nil
	}
	out := new(PersesImportantDashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesIngress) DeepCopyInto(out *PersesIngress) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]PersesIngressHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]PersesIngressTLS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesIngress.
func (in *PersesIngress) DeepCopy() *PersesIngress {
	if in == nil {
		return nil
	}
	out := new(PersesIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesIngressHost) DeepCopyInto(out *PersesIngressHost) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]PersesIngressPath, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesIngressHost.
func (in *PersesIngressHost) DeepCopy() *PersesIngressHost {
	if in == nil {
		return nil
	}
	out := new(PersesIngressHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesIngressPath) DeepCopyInto(out *PersesIngressPath) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesIngressPath.
func (in *PersesIngressPath) DeepCopy() *PersesIngressPath {
	if in == nil {
		return nil
	}
	out := new(PersesIngressPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesIngressTLS) DeepCopyInto(out *PersesIngressTLS) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesIngressTLS.
func (in *PersesIngressTLS) DeepCopy() *PersesIngressTLS {
	if in == nil {
		return nil
	}
	out := new(PersesIngressTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesList) DeepCopyInto(out *PersesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Perses, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesList.
func (in *PersesList) DeepCopy() *PersesList {
	if in == nil {
		return nil
	}
	out := new(PersesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PersesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesPersistence) DeepCopyInto(out *PersesPersistence) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesPersistence.
func (in *PersesPersistence) DeepCopy() *PersesPersistence {
	if in == nil {
		return nil
	}
	out := new(PersesPersistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesProbe) DeepCopyInto(out *PersesProbe) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesProbe.
func (in *PersesProbe) DeepCopy() *PersesProbe {
	if in == nil {
		return nil
	}
	out := new(PersesProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesProvisioningPersistence) DeepCopyInto(out *PersesProvisioningPersistence) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesProvisioningPersistence.
func (in *PersesProvisioningPersistence) DeepCopy() *PersesProvisioningPersistence {
	if in == nil {
		return nil
	}
	out := new(PersesProvisioningPersistence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesService) DeepCopyInto(out *PersesService) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesService.
func (in *PersesService) DeepCopy() *PersesService {
	if in == nil {
		return nil
	}
	out := new(PersesService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesServiceMonitor) DeepCopyInto(out *PersesServiceMonitor) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesServiceMonitor.
func (in *PersesServiceMonitor) DeepCopy() *PersesServiceMonitor {
	if in == nil {
		return nil
	}
	out := new(PersesServiceMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesServiceMonitorSelector) DeepCopyInto(out *PersesServiceMonitorSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesServiceMonitorSelector.
func (in *PersesServiceMonitorSelector) DeepCopy() *PersesServiceMonitorSelector {
	if in == nil {
		return nil
	}
	out := new(PersesServiceMonitorSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesSidecar) DeepCopyInto(out *PersesSidecar) {
	*out = *in
	out.Image = in.Image
	if in.ExtraEnvVars != nil {
		in, out := &in.ExtraEnvVars, &out.ExtraEnvVars
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesSidecar.
func (in *PersesSidecar) DeepCopy() *PersesSidecar {
	if in == nil {
		return nil
	}
	out := new(PersesSidecar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesSidecarImage) DeepCopyInto(out *PersesSidecarImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesSidecarImage.
func (in *PersesSidecarImage) DeepCopy() *PersesSidecarImage {
	if in == nil {
		return nil
	}
	out := new(PersesSidecarImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesSpec) DeepCopyInto(out *PersesSpec) {
	*out = *in
	out.Image = in.Image
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
	in.Service.DeepCopyInto(&out.Service)
	in.ServiceMonitor.DeepCopyInto(&out.ServiceMonitor)
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	out.LivenessProbe = in.LivenessProbe
	out.ReadinessProbe = in.ReadinessProbe
	in.Resources.DeepCopyInto(&out.Resources)
	in.Config.DeepCopyInto(&out.Config)
	in.ProvisioningPersistence.DeepCopyInto(&out.ProvisioningPersistence)
	if in.EnvVars != nil {
		in, out := &in.EnvVars, &out.EnvVars
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Sidecar.DeepCopyInto(&out.Sidecar)
	in.Persistence.DeepCopyInto(&out.Persistence)
	in.Ingress.DeepCopyInto(&out.Ingress)
	out.TLS = in.TLS
	out.Distro = in.Distro
	if in.Datasources != nil {
		in, out := &in.Datasources, &out.Datasources
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraObjects != nil {
		in, out := &in.ExtraObjects, &out.ExtraObjects
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.OciArtifacts != nil {
		in, out := &in.OciArtifacts, &out.OciArtifacts
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	out.TestFramework = in.TestFramework
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesSpec.
func (in *PersesSpec) DeepCopy() *PersesSpec {
	if in == nil {
		return nil
	}
	out := new(PersesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesTLS) DeepCopyInto(out *PersesTLS) {
	*out = *in
	out.CaCert = in.CaCert
	out.ClientCert = in.ClientCert
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesTLS.
func (in *PersesTLS) DeepCopy() *PersesTLS {
	if in == nil {
		return nil
	}
	out := new(PersesTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesTLSCert) DeepCopyInto(out *PersesTLSCert) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesTLSCert.
func (in *PersesTLSCert) DeepCopy() *PersesTLSCert {
	if in == nil {
		return nil
	}
	out := new(PersesTLSCert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesTestFramework) DeepCopyInto(out *PersesTestFramework) {
	*out = *in
	out.Image = in.Image
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesTestFramework.
func (in *PersesTestFramework) DeepCopy() *PersesTestFramework {
	if in == nil {
		return nil
	}
	out := new(PersesTestFramework)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersesTestFrameworkImage) DeepCopyInto(out *PersesTestFrameworkImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersesTestFrameworkImage.
func (in *PersesTestFrameworkImage) DeepCopy() *PersesTestFrameworkImage {
	if in == nil {
		return nil
	}
	out := new(PersesTestFrameworkImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresqlAuth) DeepCopyInto(out *PostgresqlAuth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresqlAuth.
func (in *PostgresqlAuth) DeepCopy() *PostgresqlAuth {
	if in == nil {
		return nil
	}
	out := new(PostgresqlAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresqlSpec) DeepCopyInto(out *PostgresqlSpec) {
	*out = *in
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(PostgresqlAuth)
		**out = **in
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalPostgresql)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresqlSpec.
func (in *PostgresqlSpec) DeepCopy() *PostgresqlSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresqlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxy) DeepCopyInto(out *PromLabelProxy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxy.
func (in *PromLabelProxy) DeepCopy() *PromLabelProxy {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PromLabelProxy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyAutoscaling) DeepCopyInto(out *PromLabelProxyAutoscaling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyAutoscaling.
func (in *PromLabelProxyAutoscaling) DeepCopy() *PromLabelProxyAutoscaling {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyAutoscaling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyClickhouse) DeepCopyInto(out *PromLabelProxyClickhouse) {
	*out = *in
	in.TLS.DeepCopyInto(&out.TLS)
	in.Storage.DeepCopyInto(&out.Storage)
	in.ClusterTopology.DeepCopyInto(&out.ClusterTopology)
	out.S3 = in.S3
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyClickhouse.
func (in *PromLabelProxyClickhouse) DeepCopy() *PromLabelProxyClickhouse {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyClickhouse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyClickhouseCertRef) DeepCopyInto(out *PromLabelProxyClickhouseCertRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyClickhouseCertRef.
func (in *PromLabelProxyClickhouseCertRef) DeepCopy() *PromLabelProxyClickhouseCertRef {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyClickhouseCertRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyClickhouseCluster) DeepCopyInto(out *PromLabelProxyClickhouseCluster) {
	*out = *in
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyClickhouseCluster.
func (in *PromLabelProxyClickhouseCluster) DeepCopy() *PromLabelProxyClickhouseCluster {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyClickhouseCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyClickhouseClusterTopology) DeepCopyInto(out *PromLabelProxyClickhouseClusterTopology) {
	*out = *in
	in.ClickHouseKeeper.DeepCopyInto(&out.ClickHouseKeeper)
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyClickhouseClusterTopology.
func (in *PromLabelProxyClickhouseClusterTopology) DeepCopy() *PromLabelProxyClickhouseClusterTopology {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyClickhouseClusterTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyClickhouseKeeper) DeepCopyInto(out *PromLabelProxyClickhouseKeeper) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyClickhouseKeeper.
func (in *PromLabelProxyClickhouseKeeper) DeepCopy() *PromLabelProxyClickhouseKeeper {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyClickhouseKeeper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyClickhousePodSpec) DeepCopyInto(out *PromLabelProxyClickhousePodSpec) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyClickhousePodSpec.
func (in *PromLabelProxyClickhousePodSpec) DeepCopy() *PromLabelProxyClickhousePodSpec {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyClickhousePodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyClickhousePodTemplate) DeepCopyInto(out *PromLabelProxyClickhousePodTemplate) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyClickhousePodTemplate.
func (in *PromLabelProxyClickhousePodTemplate) DeepCopy() *PromLabelProxyClickhousePodTemplate {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyClickhousePodTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyClickhouseS3) DeepCopyInto(out *PromLabelProxyClickhouseS3) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyClickhouseS3.
func (in *PromLabelProxyClickhouseS3) DeepCopy() *PromLabelProxyClickhouseS3 {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyClickhouseS3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyClickhouseTLS) DeepCopyInto(out *PromLabelProxyClickhouseTLS) {
	*out = *in
	if in.ClientCaCertificateRefs != nil {
		in, out := &in.ClientCaCertificateRefs, &out.ClientCaCertificateRefs
		*out = make([]PromLabelProxyClickhouseCertRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyClickhouseTLS.
func (in *PromLabelProxyClickhouseTLS) DeepCopy() *PromLabelProxyClickhouseTLS {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyClickhouseTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyConfig) DeepCopyInto(out *PromLabelProxyConfig) {
	*out = *in
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyConfig.
func (in *PromLabelProxyConfig) DeepCopy() *PromLabelProxyConfig {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyImage) DeepCopyInto(out *PromLabelProxyImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyImage.
func (in *PromLabelProxyImage) DeepCopy() *PromLabelProxyImage {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyIngress) DeepCopyInto(out *PromLabelProxyIngress) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]PromLabelProxyIngressHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]PromLabelProxyIngressTLS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyIngress.
func (in *PromLabelProxyIngress) DeepCopy() *PromLabelProxyIngress {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyIngressHost) DeepCopyInto(out *PromLabelProxyIngressHost) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]PromLabelProxyIngressPath, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyIngressHost.
func (in *PromLabelProxyIngressHost) DeepCopy() *PromLabelProxyIngressHost {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyIngressHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyIngressPath) DeepCopyInto(out *PromLabelProxyIngressPath) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyIngressPath.
func (in *PromLabelProxyIngressPath) DeepCopy() *PromLabelProxyIngressPath {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyIngressPath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyIngressTLS) DeepCopyInto(out *PromLabelProxyIngressTLS) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyIngressTLS.
func (in *PromLabelProxyIngressTLS) DeepCopy() *PromLabelProxyIngressTLS {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyIngressTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyKubeRBACProxy) DeepCopyInto(out *PromLabelProxyKubeRBACProxy) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	out.Image = in.Image
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ContainerSecurityContext != nil {
		in, out := &in.ContainerSecurityContext, &out.ContainerSecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyKubeRBACProxy.
func (in *PromLabelProxyKubeRBACProxy) DeepCopy() *PromLabelProxyKubeRBACProxy {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyKubeRBACProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyList) DeepCopyInto(out *PromLabelProxyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PromLabelProxy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyList.
func (in *PromLabelProxyList) DeepCopy() *PromLabelProxyList {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PromLabelProxyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyMetrics) DeepCopyInto(out *PromLabelProxyMetrics) {
	*out = *in
	in.ServiceMonitor.DeepCopyInto(&out.ServiceMonitor)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyMetrics.
func (in *PromLabelProxyMetrics) DeepCopy() *PromLabelProxyMetrics {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyPlatform) DeepCopyInto(out *PromLabelProxyPlatform) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyPlatform.
func (in *PromLabelProxyPlatform) DeepCopy() *PromLabelProxyPlatform {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyProbe) DeepCopyInto(out *PromLabelProxyProbe) {
	*out = *in
	out.HttpGet = in.HttpGet
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyProbe.
func (in *PromLabelProxyProbe) DeepCopy() *PromLabelProxyProbe {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyProbeHttpGet) DeepCopyInto(out *PromLabelProxyProbeHttpGet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyProbeHttpGet.
func (in *PromLabelProxyProbeHttpGet) DeepCopy() *PromLabelProxyProbeHttpGet {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyProbeHttpGet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyService) DeepCopyInto(out *PromLabelProxyService) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyService.
func (in *PromLabelProxyService) DeepCopy() *PromLabelProxyService {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyServiceMonitor) DeepCopyInto(out *PromLabelProxyServiceMonitor) {
	*out = *in
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TargetLabels != nil {
		in, out := &in.TargetLabels, &out.TargetLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodTargetLabels != nil {
		in, out := &in.PodTargetLabels, &out.PodTargetLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HonorTimestamps != nil {
		in, out := &in.HonorTimestamps, &out.HonorTimestamps
		*out = new(bool)
		**out = **in
	}
	if in.AttachMetadata != nil {
		in, out := &in.AttachMetadata, &out.AttachMetadata
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Relabelings != nil {
		in, out := &in.Relabelings, &out.Relabelings
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.MetricRelabelings != nil {
		in, out := &in.MetricRelabelings, &out.MetricRelabelings
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalConfigs != nil {
		in, out := &in.AdditionalConfigs, &out.AdditionalConfigs
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalEndpointConfigs != nil {
		in, out := &in.AdditionalEndpointConfigs, &out.AdditionalEndpointConfigs
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyServiceMonitor.
func (in *PromLabelProxyServiceMonitor) DeepCopy() *PromLabelProxyServiceMonitor {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyServiceMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxySpec) DeepCopyInto(out *PromLabelProxySpec) {
	*out = *in
	out.Image = in.Image
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Service.DeepCopyInto(&out.Service)
	in.Resources.DeepCopyInto(&out.Resources)
	out.Autoscaling = in.Autoscaling
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.LivenessProbe = in.LivenessProbe
	out.ReadinessProbe = in.ReadinessProbe
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Config.DeepCopyInto(&out.Config)
	in.Metrics.DeepCopyInto(&out.Metrics)
	in.KubeRBACProxy.DeepCopyInto(&out.KubeRBACProxy)
	in.Clickhouse.DeepCopyInto(&out.Clickhouse)
	in.Infra.DeepCopyInto(&out.Infra)
	out.Platform = in.Platform
	out.Distro = in.Distro
	if in.ExtraManifests != nil {
		in, out := &in.ExtraManifests, &out.ExtraManifests
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxySpec.
func (in *PromLabelProxySpec) DeepCopy() *PromLabelProxySpec {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromLabelProxyStorage) DeepCopyInto(out *PromLabelProxyStorage) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromLabelProxyStorage.
func (in *PromLabelProxyStorage) DeepCopy() *PromLabelProxyStorage {
	if in == nil {
		return nil
	}
	out := new(PromLabelProxyStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConfig) DeepCopyInto(out *PrometheusConfig) {
	*out = *in
	out.BasicAuth = in.BasicAuth
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConfig.
func (in *PrometheusConfig) DeepCopy() *PrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitmqSecret) DeepCopyInto(out *RabbitmqSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitmqSecret.
func (in *RabbitmqSecret) DeepCopy() *RabbitmqSecret {
	if in == nil {
		return nil
	}
	out := new(RabbitmqSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitmqSpec) DeepCopyInto(out *RabbitmqSpec) {
	*out = *in
	out.Image = in.Image
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitmqSpec.
func (in *RabbitmqSpec) DeepCopy() *RabbitmqSpec {
	if in == nil {
		return nil
	}
	out := new(RabbitmqSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Spec) DeepCopyInto(out *S3Spec) {
	*out = *in
	out.Image = in.Image
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Spec.
func (in *S3Spec) DeepCopy() *S3Spec {
	if in == nil {
		return nil
	}
	out := new(S3Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountSpec) DeepCopyInto(out *ServiceAccountSpec) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountSpec.
func (in *ServiceAccountSpec) DeepCopy() *ServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMonitorLabels) DeepCopyInto(out *ServiceMonitorLabels) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMonitorLabels.
func (in *ServiceMonitorLabels) DeepCopy() *ServiceMonitorLabels {
	if in == nil {
		return nil
	}
	out := new(ServiceMonitorLabels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMonitorSpec) DeepCopyInto(out *ServiceMonitorSpec) {
	*out = *in
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMonitorSpec.
func (in *ServiceMonitorSpec) DeepCopy() *ServiceMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServingCerts) DeepCopyInto(out *ServingCerts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServingCerts.
func (in *ServingCerts) DeepCopy() *ServingCerts {
	if in == nil {
		return nil
	}
	out := new(ServingCerts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantOperator) DeepCopyInto(out *TenantOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantOperator.
func (in *TenantOperator) DeepCopy() *TenantOperator {
	if in == nil {
		return nil
	}
	out := new(TenantOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantOperatorList) DeepCopyInto(out *TenantOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TenantOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantOperatorList.
func (in *TenantOperatorList) DeepCopy() *TenantOperatorList {
	if in == nil {
		return nil
	}
	out := new(TenantOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantOperatorSpec) DeepCopyInto(out *TenantOperatorSpec) {
	*out = *in
	in.Image.DeepCopyInto(&out.Image)
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
	out.Apiserver = in.Apiserver
	in.Monitoring.DeepCopyInto(&out.Monitoring)
	out.Distro = in.Distro
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantOperatorSpec.
func (in *TenantOperatorSpec) DeepCopy() *TenantOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(TenantOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosFeatureFlag) DeepCopyInto(out *ThanosFeatureFlag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosFeatureFlag.
func (in *ThanosFeatureFlag) DeepCopy() *ThanosFeatureFlag {
	if in == nil {
		return nil
	}
	out := new(ThanosFeatureFlag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosObjectStorage) DeepCopyInto(out *ThanosObjectStorage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosObjectStorage.
func (in *ThanosObjectStorage) DeepCopy() *ThanosObjectStorage {
	if in == nil {
		return nil
	}
	out := new(ThanosObjectStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosOperator) DeepCopyInto(out *ThanosOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosOperator.
func (in *ThanosOperator) DeepCopy() *ThanosOperator {
	if in == nil {
		return nil
	}
	out := new(ThanosOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThanosOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosOperatorCrd) DeepCopyInto(out *ThanosOperatorCrd) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosOperatorCrd.
func (in *ThanosOperatorCrd) DeepCopy() *ThanosOperatorCrd {
	if in == nil {
		return nil
	}
	out := new(ThanosOperatorCrd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosOperatorImage) DeepCopyInto(out *ThanosOperatorImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosOperatorImage.
func (in *ThanosOperatorImage) DeepCopy() *ThanosOperatorImage {
	if in == nil {
		return nil
	}
	out := new(ThanosOperatorImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosOperatorList) DeepCopyInto(out *ThanosOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ThanosOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosOperatorList.
func (in *ThanosOperatorList) DeepCopy() *ThanosOperatorList {
	if in == nil {
		return nil
	}
	out := new(ThanosOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ThanosOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosOperatorManager) DeepCopyInto(out *ThanosOperatorManager) {
	*out = *in
	out.Image = in.Image
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvOverrides != nil {
		in, out := &in.EnvOverrides, &out.EnvOverrides
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosOperatorManager.
func (in *ThanosOperatorManager) DeepCopy() *ThanosOperatorManager {
	if in == nil {
		return nil
	}
	out := new(ThanosOperatorManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosOperatorMetrics) DeepCopyInto(out *ThanosOperatorMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosOperatorMetrics.
func (in *ThanosOperatorMetrics) DeepCopy() *ThanosOperatorMetrics {
	if in == nil {
		return nil
	}
	out := new(ThanosOperatorMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosOperatorSpec) DeepCopyInto(out *ThanosOperatorSpec) {
	*out = *in
	in.Manager.DeepCopyInto(&out.Manager)
	out.RbacHelpers = in.RbacHelpers
	out.Crd = in.Crd
	out.Metrics = in.Metrics
	out.CertManager = in.CertManager
	out.Prometheus = in.Prometheus
	out.ObjectStorage = in.ObjectStorage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosOperatorSpec.
func (in *ThanosOperatorSpec) DeepCopy() *ThanosOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(ThanosOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThanosRbacHelpers) DeepCopyInto(out *ThanosRbacHelpers) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThanosRbacHelpers.
func (in *ThanosRbacHelpers) DeepCopy() *ThanosRbacHelpers {
	if in == nil {
		return nil
	}
	out := new(ThanosRbacHelpers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TikaSpec) DeepCopyInto(out *TikaSpec) {
	*out = *in
	out.Image = in.Image
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TikaSpec.
func (in *TikaSpec) DeepCopy() *TikaSpec {
	if in == nil {
		return nil
	}
	out := new(TikaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebHookSpec) DeepCopyInto(out *WebHookSpec) {
	*out = *in
	out.Healthcheck = in.Healthcheck
	out.ServingCerts = in.ServingCerts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebHookSpec.
func (in *WebHookSpec) DeepCopy() *WebHookSpec {
	if in == nil {
		return nil
	}
	out := new(WebHookSpec)
	in.DeepCopyInto(out)
	return out
}
