apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenant-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tenant-operator.labels" . | nindent 4 }}
{{- if eq "prometheus.io/builtin" ( include "monitoring.agent" . ) }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
{{- end }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    {{- include "tenant-operator.selectorLabels" . | nindent 4 }}
