apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prom-label-proxy.fullname" . }}
  namespace: {{ template "prom-label-proxy.namespace" . }}
  labels:
    {{- include "prom-label-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prom-label-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if or .Values.podAnnotations (and .Values.kubeRBACProxy.enabled .Values.kubeRBACProxy.config) }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if and .Values.kubeRBACProxy.enabled .Values.kubeRBACProxy.config }}
        checksum/config: {{ .Values.kubeRBACProxy.config | toJson | sha256sum }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "prom-label-proxy.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prom-label-proxy.serviceAccountName" . }}
      {{- if eq "true" ( include "distro.openshift" . ) }}
      securityContext:
        {{- toYaml (omit .Values.podSecurityContext "runAsUser" "runAsGroup" "fsGroup" "supplementalGroups") | nindent 8 }}
      {{- else }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
      {{- $configListenPort := tpl .Values.config.listenAddress $ | splitList ":" | last }}
        - name: {{ .Chart.Name }}
          {{- if eq "true" ( include "distro.openshift" . ) }}
          securityContext:
            {{- toYaml (omit .Values.securityContext "runAsUser" "runAsGroup" "fsGroup" "supplementalGroups") | nindent 12 }}
          {{- else }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--insecure-listen-address={{ tpl .Values.config.listenAddress $ }}"
            - --upstream=http://thanos-query-telemetry-stack.monitoring.svc:9090/
            - "--label={{ tpl .Values.config.label $ }}"
            {{- if .Values.metrics.enabled }}
            - "--internal-listen-address={{ tpl .Values.metrics.listenAddress $ }}"
            {{- end }}
            - --tls-cert-file=/etc/proxy-tls/tls.crt
            - --tls-key-file=/etc/proxy-tls/tls.key
            - --tls-ca-file=/etc/proxy-tls/ca.crt
            - --require-client-cert=true
            - --cert-auth-ou=EnableTenant=True
            {{- with .Values.config.extraArgs }}
              {{- tpl (typeIs "string" . | ternary . (. | toYaml)) $ | nindent 12 }}
            {{- end }}
          env:
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: monitoring-clickhouse-auth
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: monitoring-clickhouse-auth
            - name: LOGS_URL
              value: http://monitoring-clickhouse.monitoring.svc:8123
            - name: TRACES_URL
              value: http://monitoring-clickhouse.monitoring.svc:8123
            - name: METRICS_URL
              value: http://thanos-receive-router-telemetry-stack.monitoring.svc:19291
            - name: PLATFORM_APISERVER_DOMAIN
              value: {{ .Values.platform.baseURL }}
          ports:
            - name: http
              containerPort: {{ $configListenPort }}
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: http-metrics
              containerPort: {{ splitList ":" .Values.metrics.listenAddress | last }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/proxy-tls
              name: proxy-tls
              readOnly: true
        {{-  if .Values.kubeRBACProxy.enabled  }}
        - name: kube-rbac-proxy
          args:
          {{-  if .Values.kubeRBACProxy.extraArgs  }}
          {{- .Values.kubeRBACProxy.extraArgs | toYaml | nindent 10 }}
          {{-  end  }}
          - --secure-listen-address=:{{ .Values.kubeRBACProxy.port }}
          - --upstream=http://127.0.0.1:{{ $configListenPort }}/
          - --proxy-endpoints-port=8888
          {{- if .Values.kubeRBACProxy.config }}
          - --config-file=/etc/kube-rbac-proxy-config/config-file.yaml
          {{- end }}
          volumeMounts:
            - name: kube-rbac-proxy-config
              mountPath: /etc/kube-rbac-proxy-config
            {{- with .Values.kubeRBACProxy.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - mountPath: /etc/proxy-tls
              name: proxy-tls
              readOnly: true
          imagePullPolicy: {{ .Values.kubeRBACProxy.image.pullPolicy }}
          image: {{ include "kubeRBACProxy.image" . }}
          ports:
            - containerPort: {{ .Values.kubeRBACProxy.port }}
              name: krp
            - containerPort: 8888
              name: krp-healthz
          readinessProbe:
            httpGet:
              scheme: HTTPS
              port: 8888
              path: healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          {{- if .Values.kubeRBACProxy.resources }}
          resources: {{ toYaml .Values.kubeRBACProxy.resources | nindent 10 }}
          {{- end }}
          {{- if .Values.kubeRBACProxy.containerSecurityContext }}
          {{- if eq "true" ( include "distro.openshift" . ) }}
          securityContext:
            {{- toYaml (omit .Values.kubeRBACProxy.containerSecurityContext "runAsUser" "runAsGroup" "fsGroup" "supplementalGroups") | nindent 12 }}
          {{- else }}
          securityContext:
             {{- toYaml .Values.kubeRBACProxy.containerSecurityContext | nindent 12 }}
          {{- end }}
          {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: proxy-tls
          secret:
            defaultMode: 420
            secretName: {{ include "prom-label-proxy.name" . }}-gw-cert
      {{-  if and .Values.kubeRBACProxy.enabled .Values.kubeRBACProxy.config }}
        - name: kube-rbac-proxy-config
          configMap:
            name: {{ template "prom-label-proxy.fullname" . }}-rbac-config
      {{- end }}
