apiVersion: v1
kind: Secret
metadata:
  name: thanos-ruler-query-config
  namespace: {{ .Release.Namespace }}
stringData:
  query.yaml: |
    - http_config:
        tls_config:
          cert_file: /etc/certs/tls.crt
          key_file: /etc/certs/tls.key
          ca_file: /etc/certs/ca.crt
          server_name: prom-label-proxy.monitoring.svc.cluster.local
      static_configs:
        - "{{ .Values.monitoringClusterBaseURL }}:10001"
      scheme: https

---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-ruler-remote-write-config
  namespace: {{ .Release.Namespace }}
stringData:
  remote-write.yaml: |
    remote_write:
      - url: https://{{ .Values.monitoringClusterBaseURL }}:10001/api/v1/receive
        tls_config:
          cert_file: /etc/certs/tls.crt
          key_file: /etc/certs/tls.key
          ca_file: /etc/certs/ca.crt
          server_name: prom-label-proxy.monitoring.svc.cluster.local
        headers:
          Thanos-Tenant: default
