project:
  name: Perses by AppsCode
  shortName: Perses
  url: https://github.com/perses/perses
  description: Perses helm chart
  app: a Perses
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: perses
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.21+
release:
  name: perses
  namespace: monitoring
